- name: fetch ubuntu netboot tarball
  get_url:
    url: "{{ ubuntu_netboot_url }}"
    dest: "/root/netboot.tar.gz"
    checksum: "{{ ubuntu_netboot_checksum }}"
- name: extract netboot ubuntu files
  command:
    cmd: tar xzf /root/netboot.tar.gz -C /root/netboot
  args:
    creates: /root/netboot/ubuntu-installer/amd64/linux
- name: copy netboot ubuntu files
  copy:
    src: "/root/netboot/{{ item }}"
    dest: "{{ tftp_root }}/netboot/ubuntu18/"
    remote_src: yes
  loop:
    - "ubuntu-installer/amd64/linux"
    - "ubuntu-installer/amd64/initrd.gz"
